### ISSUE TITLE
Upstream merges to smartborders and pointer-constraints branches

### ISSUE THREAD

**Issue by fauxmight** [sevz17/dwl#22]
@sevz17 : These are the first merges to your repository since you added write permissions.

Please take a look when you have the chance.
Let me know if there are any style changes you would like.
Let me know if there are any commit message changes you would like.

In general, these are your branches/patches and your repository; I want to be sure moving forward that maintenance I do is in keeping with your preferences.

**Comment by sevz17** [comment]
First of all, thanks for keeping up to date my patches!

There's something I had to tell you but I caught a cold and forgot it :), the proper way to update patches is rebasing rather than merging, `git format-patch` omits merge commits when showing patches, thus when you download the patch from the link in the wiki, the patch fails to apply because git shows the commit as it was commited, ignoring the merged changes.

Apart from https://github.com/sevz17/dwl/commit/c82e8976b6bc1edc10eda88f254603c318cb1eb5#r94386853 and the rebase thing, all seems fine.

About the commit messages since you will be rebasing, the commit messages shouldn't be a issue, just add the tag `Co-authored-by: Leonardo Hernández Hernández <leohdz172@protonmail.com>` (with your git info) at the bottom of the commit message, just like the pointer-constraints patch.

And also please remember to update the date in the wiki's patch page (it isn't really necessary but tells people that the patch is actually updated).

Oh, and if you want to do changes unrelated to updating them, fell free to do so, or if you are not sure about changes, open a pr and I will review them.

**Comment by fauxmight** [comment]
Thank you for the clear and concise feedback.
I appreciate specifically the instruction regarding rebasing rather than merging updates to a patch.

As soon as I can, I will address these points and clean up the modifications on the smartborders and the pointer-constraints branches.
